export type BELL_NOTIFICATION_TYPE =
  | 'USER_LINKED_IN_A_NEW_GROUP'
  | 'USER_REQUESTED_MISSION_ENROLLMENT_DEADLINE_EXTENSION'
  | 'NEW_MISSION_LINKED_IN_THE_GROUP'
  | 'NEW_TRAIL_LINKED_IN_THE_GROUP'
  | 'MISSION_TRAIL_ENABLED'
  | 'MISSION_TRAIL_DISABLED'
  | 'MISSION_TRAIL_DISABLED_FOR_TOO_LONG'
  | 'NEW_TRAIL_PUBLISHED'
  | 'LEARNING_TRAIL_HAS_EXPIRED'
  | 'LEARNING_TRAIL_HAS_BEEN_TRANSFERRED_TO_YOU'
  | 'MISSION_MINIMUM_PERFORMANCE_UPDATED'
  | 'NEW_MISSION_EVALUATION'
  | 'MISSION_IN_REVIEW'
  | 'MISSION_MODIFIED_BY_CONTRIBUTOR'
  | 'MISSION_TRANSFERRED_TO_YOU'
  | 'MISSION_HAS_BEEN_DUPLICATED'
  | 'MISSION_HAS_BEEN_MOVED'
  | 'MISSION_HAS_BEEN_MOVED_TO_YOUR_WORKSPACE'
  | 'NEW_QUIZ_ADDED_IN_THE_CHANNEL'
  | 'NEW_PULSE_ADDED_IN_THE_CHANNEL'
  | 'NEW_CHANNEL_COMMENT'
  | 'NEW_PULSE_COMMENT'
  | 'CHANNEL_TRANSFERRED_TO_YOU'
  | 'ENROLLED_IN_A_TRAIL'
  | 'LEARNING_TRAIL_ENROLLMENT_EXPIRING'
  | 'MISSION_ENROLLMENT_HAS_BEEN_RESTARTED'
  | 'REPROVED_ENROLLMENT_HAS_BEEN_MANUALLY_APPROVED'
  | 'NEW_EXTERNAL_ENROLLMENT_CERTIFICATE_TO_REVIEW'
  | 'EXTERNAL_ENROLLMENT_REVIEWED'
  | 'MISSION_ENROLLMENT_REFUSED'
  | 'MISSION_ENROLLMENT_APPROVED'
  | 'MISSION_ENROLLMENT_HAS_EXPIRED'
  | 'ENROLLED_IN_A_MISSION'
  | 'MISSION_ENROLLMENT_DEADLINE_HAS_BEEN_EXTENDED'
  | 'ENROLLED_IN_A_LEARNING_TRAIL'
  | 'MISSION_ENROLLMENT_IS_EXPIRING'
  | 'NEW_CHANNEL_LINKED_IN_THE_GROUP'
  | 'MIRRORED_COURSE_EVALUATION';

export type BELL_NOTIFICATION_STATUS = 'READ' | 'SENT' | 'UNREAD';

export type BELL_NOTIFICATION_ACTION_TYPE = 'NOTHING' | 'FORWARD_URL' | 'DOWNLOAD';

export interface NotificationPage<T> {
  count: number;
  page: number;
  limit: number;
  results: T[];
}

export interface BellNotification {
  id: string;
  title: string;
  message: string;
  action: BELL_NOTIFICATION_ACTION_TYPE;
  status: BELL_NOTIFICATION_STATUS;
  createdAt: Date;
  typeKey: BELL_NOTIFICATION_TYPE;
  objectPk: string;
}
