import { marker } from '@jsverse/transloco-keys-manager/marker';

marker('CHANNEL.SUBSCRIBED_SUCCESS');
marker('CHANNEL.SAVE.SUCCESS');
marker('CHANNEL.CONSULT.CONTRIBUTORS.ERROR');
marker('CHANNEL.SAVE.CONTRIBUTORS.SUCCESS');
marker('CHANNEL.SAVE.CONTRIBUTORS.ERROR');
marker('CHANNEL.REMOVE.CONTRIBUTORS.SUCCESS');
marker('CHANNEL.REMOVE.CONTRIBUTORS.ERROR');
marker('CHANNEL.INACTIVE');
marker('CHANNEL.DETAIL.ENROLLMENTS.SINGULAR');
marker('CHANNEL.DETAIL.ENROLLMENTS.PLURAL');
marker('CHANNEL.DETAIL.CONTRIBUTORS.SINGULAR');
marker('CHANNEL.DETAIL.CONTRIBUTORS.PLURAL');
marker('CHANNEL.DETAIL.PULSES.SINGULAR');
marker('CHANNEL.DETAIL.PULSES.PLURAL');
marker('BATCH_ENROLLMENT.ENROLLED_COUNTER.SINGULAR');
marker('BATCH_ENROLLMENT.ENROLLED_COUNTER.PLURAL');
marker('BATCH_ENROLLMENT.ENROLLED_SUCCESS_LABEL.SINGULAR');
marker('BATCH_ENROLLMENT.ENROLLED_SUCCESS_LABEL.PLURAL');
marker('MISSION.STEP.EDIT_TOPIC');
marker('MISSION.STEP.NEW_MISSION');
marker('MISSION.STEP.INFORMATION_BASIC');
marker('MISSION.STEP.ADD_NEW_CONTENT');
marker('MISSION.STEP.ADD_NEW_CONTENT_INFORMATION');
marker('MISSION.QUIZ.NOTICE');
marker('MISSION.QUIZ.DELETE_QUESTION');
marker('MISSION.DETAIL.TYPE.PRESENTIAL');
marker('MISSION.DETAIL.TYPE.LIVE');
marker('MISSION.DETAIL.CONFIRMED.PLURAL');
marker('MISSION.DETAIL.CONFIRMED.SINGULAR');
marker('MISSION.DETAIL.CLOSE_TO_END.PLURAL');
marker('MISSION.DETAIL.CLOSE_TO_END.SINGULAR');
marker('MISSION.DETAIL.INSTRUCTORS.SINGULAR');
marker('MISSION.DETAIL.INSTRUCTORS.PLURAL');
marker('MISSION.DETAIL.MESSAGE_DELETE');
marker('MISSION.DETAIL.MESSAGE_DELETE_TRAIL_LINK');
marker('MISSION.DETAIL.MESSAGE_DELETE_SUCCESS');
marker('MISSION.DETAIL.MESSAGE_DELETE_ERROR');
marker('MISSION.DETAIL.CONFIRM_GIVE_UP');
marker('MISSION.DETAIL.SUCCESS_GIVE_UP');
marker('MISSION.DETAIL.ERROR_GIVE_UP');
marker('MISSION.DETAIL.CONFIRM_RESUME');
marker('MISSION.DETAIL.SUCCESS_RESUME');
marker('MISSION.DETAIL.ERROR_RESUME');
marker('MISSION.ATTENDANCE_LIST.TITLE');
marker('MISSION.ATTENDANCE_LIST.UNTIL');
marker('MISSION.ATTENDANCE_LIST.ALL_DATES');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION_PERCENTAGE');
marker('MISSION.ATTENDANCE_LIST.ATTENDANCE_PERCENTAGE');
marker('MISSION.ATTENDANCE_LIST.CLOSE_LIST');
marker('MISSION.ATTENDANCE_LIST.REOPEN_LIST');
marker('MISSION.ATTENDANCE_LIST.PRINT');
marker('MISSION.ATTENDANCE_LIST.PRESENT.PLURAL');
marker('MISSION.ATTENDANCE_LIST.PRESENT.SINGULAR');
marker('MISSION.ATTENDANCE_LIST.LAST_CONFIRMATIONS.TITLE');
marker('MISSION.ATTENDANCE_LIST.LAST_CONFIRMATIONS.MESSAGE');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.TITLE');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.SEARCH_PLACEHOLDER');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.NAME');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.EMAIL');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.PRESENCE');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.YES');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.NO');
marker('MISSION.ATTENDANCE_LIST.CONFIRMATION.SELECT_ALL');
marker('MISSION.ATTENDANCE_LIST.UPDATE_PRESENTED_SUCCESS');
marker('MISSION.ATTENDANCE_LIST.BATCH_UPDATE_PRESENTED_SUCCESS');
marker('MISSION.ATTENDANCE_LIST.ATTENDANCE_LIST_CLOSED');
marker('MISSION.ATTENDANCE_LIST.ATTENDANCE_LIST_REOPENED');
marker('MISSION.ATTENDANCE_LIST.SELECTION_LABEL.PLURAL');
marker('MISSION.ATTENDANCE_LIST.SELECTION_LABEL.SINGULAR');
marker('CONTRIBUTORS.ERROR.CONSULT');
marker('CONTRIBUTORS.SUCCESS.SAVE');
marker('CONTRIBUTORS.ERROR.SAVE');
marker('CONTRIBUTORS.SUCCESS.REMOVED');
marker('CONTRIBUTORS.ERROR.REMOVED');
marker('CONTRIBUTORS_DIALOG.INVITED.SINGULAR');
marker('CONTRIBUTORS_DIALOG.INVITED.PLURAL');
marker('MISSION.INFO.MISSION_NOT_FOUND');
marker('MISSION.ERROR.mission_enrollment_matching_query_does_not_exist');
marker('MISSION.ERROR.mission_enrollment_invalid_status');
marker('MISSION.ERROR.mission_contributor_or_creator_cannot_be_enrolled');
marker('MISSION.ERROR.user_is_not_linked_to_any_mission_group');
marker('MISSION.ERROR.user_mission_enrollment_in_progress_already_exists');
marker('MISSION.ERROR.not_enough_seats_for_enrollments');
marker('MISSION.ERROR.file_extension_not_allowed');
marker('MISSION.ERROR.file_not_found');
marker('MISSION.ERROR.UPLOAD');
marker('MISSION.TOPIC.ADD.SUCCESS');
marker('MISSION.ERROR.ADD_TOPIC');
marker('MISSION.ERROR.CREATE_MISSION');
marker('MISSION.SUCCESS_TOPIC_REMOVED');
marker('MISSION.ERROR.TOPIC_REMOVED');
marker('MISSION.SUCCESS.TOPIC_EDIT');
marker('MISSION.ERROR.TOPIC_EDIT');
marker('MISSION.SUCCESS.REGISTRATION_COMPLETED');
marker('MISSION.ERROR.REGISTRATION_COMPLETED');
marker('MISSION.ERROR.SEARCH_TOPIC');
marker('MISSION.ERROR.EDIT_RESUME');
marker('MISSION.SUCCESS.CONTENT_REMOVED');
marker('MISSION.ERROR.CONTENT_REMOVED');
marker('MISSION.SUCCESS.CONTENT_EDIT');
marker('MISSION.ERROR.CONTENT_EDIT');
marker('MISSION.ERROR.ORDER_EDIT');
marker('MISSION.ERROR.ORDER_CONTENT');
marker('MISSION.ERROR.PUBLISH_MISSION');
marker('MISSION.ERROR.EDIT_STATUS_MISSION');
marker('PULSE.LIST.CHANNEL');
marker('PULSE.LIST.MY_CHANNEL');
marker('PULSE.LIST.PULSES');
marker('REPORT.REDEEM_CERTIFICATE');
marker('MISSION.STEP.DELETE_TOPIC_TITLE');
marker('MISSION.STEP.DELETE_TOPIC_MESSAGE');
marker('MISSION.STEP.DELETE_CONTENT_TITLE');
marker('MISSION.STEP.DELETE_CONTENT_MESSAGE');
marker('MISSION.NOT.FOUND');
marker('MISSIONS.MY_MISSIONS');
marker('MISSIONS.ALL_MISSION');
marker('MISSIONS.MY_LIST');
marker('MISSIONS.YOU_DONT_STILL_CREATED');
marker('MISSIONS.MISSIONS_TITLE');
marker('MISSIONS.NOT_EXIST_MISSIONS');
marker('MISSIONS.NOT_FIND_MISSIONS');
marker('MISSIONS.ERROR_MESSAGE');
marker('MISSIONS.TOTAL_IN_ORBIT.PLURAL');
marker('MISSIONS.TOTAL_IN_ORBIT.SINGULAR');

marker('MISSION.BOOKMARK_ADDED');
marker('MISSION.BOOKMARK_REMOVED');
marker('MISSION.BOOKMARK_REMOVED_ERROR');
marker('MISSION.LESSONS');
marker('MISSION.AVERAGE_RATING');
marker('MISSION.EXPIRED');
marker('MISSION.PUBLISHED');
marker('MISSION.AG_REVIEW');
marker('MISSION.PROCESSING');
marker('MISSION.INACTIVATED');
marker('MISSION.IN_CREATION');
marker('PULSES.ALL.NOT_FOUND');
marker('PULSE.EDIT_TITLE');
marker('PULSE.EDIT_TITLE_ERROR');
marker('PULSE.DETAIL.DELETE_PULSE');
marker('PULSE.DETAIL.CREATED_AT');
marker('PULSE.DETAIL.COMMENT');
marker('PULSE.DETAIL.COMMENTS');
marker('PULSE.DETAIL.RATE');
marker('PULSE.DETAIL.RECOMMENDED_PULSES');
marker('PULSE.DETAIL.SHARE');
marker('PULSE.DETAIL.TYPE');
marker('PULSE.DETAIL.VIEWS');
marker('PULSE.DETAIL.WRITE_COMMENT');
marker('CHANNELS.NOT_FOUND');
marker('COMMENT.EDIT');
marker('COMMENT.LABEL');
marker('COMMENT.CONFIRM_DELETE');
marker('CONFIRM.DIALOG.TITLE');
marker('EXAM_QUESTIONS.QUIZ_ANSWERED');
marker('EXAM_QUESTIONS.SAVE_RESPONSES');
marker('FILTER_MODAL.FILTER');
marker('IMAGE_UPLOAD.FILE_INVALID');
marker('NOTIFICATION.MESSAGES');
marker('NOTIFICATION.NOT_FOUND');
marker('PDF.VIEWER.WAIT');
marker('NAVIGATION.DASHBOARD');
marker('NAVIGATION.ENROLLMENTS');
marker('NAVIGATION.MISSIONS');
marker('NAVIGATION.PULSES');
marker('NAVIGATION.TRAILS');
marker('NAVIGATION.CONFIGURATIONS');
marker('NAVIGATION.NORMATIVES');
marker('NAVIGATION.GROUPS');
marker('NAVIGATION.CATEGORIES');
marker('NAVIGATION.TRANSFERS');
marker('NAVIGATION.INTEGRATIONS');
marker('NAVIGATION.POINTS_STATEMENT');
marker('GENERAL.FILE');
marker('GENERAL.LINK');
marker('GENERAL.QUIZ');
marker('GENERAL.CHANNEL-TYPE.Close For Workspace');
marker('GENERAL.CHANNEL-TYPE.Open For Workspace');
marker('GENERAL.CHANNEL-TYPE.Public');
marker('GENERAL.CHANNEL-TYPE.Paid');
marker('GENERAL.CHANNEL-TYPE.null');
marker('GENERAL.LOADING_CERTIFICATE');
marker('GENERAL.SEE_DETAILS');
marker('GENERAL.YES');
marker('GENERAL.CONTINUE');
marker('GROUP.ERROR_DIALOG.LINKING_USER_TO_KONQUEST');
marker('GROUP.ERROR_DIALOG.LINKING USER TO KONQUEST');
marker('GROUP.ERROR_DIALOG.USER_NOT_FOUND');
marker('GROUP.ERROR_DIALOG.USER NOT FOUND');
marker('GROUP.ERROR_DIALOG.GROUP_USER_ALREADY_EXISTS');
marker('GROUP.ERROR_DIALOG.USER_ALREADY_LINKED');
marker('GROUP.ERROR_DIALOG.USER_IS_NOT_LINKED_TO_ANY_MISSION_GROUP');
marker('GROUP.ERROR_DIALOG.MISSION_ENROLLMENT_ALREADY_EXISTS');
marker('GROUP.ERROR_DIALOG.GROUP_MISSION_ALREADY_EXISTS');
marker('GROUP.ERROR_DIALOG.GROUP_LEARNING_TRAIL_ALREADY_EXISTS');
marker('GROUP.ERROR_DIALOG.LEARNING_TRAIL_CREATOR_USER_CANNOT_BE_ENROLLED');
marker('GROUP.ERROR_DIALOG.GROUP_NOT_FOUND');
marker('GROUP.ERROR_DIALOG.UNEXPECTED_ERROR_HAPPENED');
marker('GROUP.ERROR_DIALOG.NOT_FOUND_LEARNING_TRAILS_OR_USERS');
marker('GROUP.ERROR_DIALOG.LEARNING_TRAIL_ENROLLMENT_ALREADY_EXISTS');
marker('GROUP.ERROR_DIALOG.USER_MISSION_ENROLLMENT_IN_PROGRESS_ALREADY_EXISTS');
marker('GROUP.ERROR_DIALOG.MISSION_CONTRIBUTOR_OR_CREATOR_CANNOT_BE_ENROLLED');

// MISSION EVALUATION
marker('COURSE.EVALUATION.FIRST_STEP.mission_evaluation_relevant_content');
marker('COURSE.EVALUATION.FIRST_STEP.mission_evaluation_basic_concepts');
marker('COURSE.EVALUATION.FIRST_STEP.mission_evaluation_practical_applicability');
marker('COURSE.EVALUATION.FIRST_STEP.mission_evaluation_content_format');
marker('COURSE.EVALUATION.FIRST_STEP.mission_evaluation_awareness');
marker('COURSE.EVALUATION.FIRST_STEP.mission_evaluation_content_time');

// UPLOAD DIALOG
marker('MISSION.CREATE.private_video');
marker('MISSION.CREATE.video_unavailable');
marker('MISSION.CREATE.video_link_error');
marker('MISSION.CREATE.imanifest_file_not_found');
marker('MISSION.CREATE.gdrive_file_size_exceeded');
marker('MISSION.CREATE.gdrive_document_not_shareable');

// CONTENTS TYPE
marker('GENERAL.CONTENT.PDF');
marker('GENERAL.CONTENT.VIDEO');
marker('GENERAL.CONTENT.IMAGE');
marker('GENERAL.CONTENT.PODCAST');
marker('GENERAL.CONTENT.BLOG');
marker('GENERAL.CONTENT.TEXT');
marker('GENERAL.CONTENT.SPREADSHEET');
marker('GENERAL.CONTENT.OTHERS');
marker('GENERAL.CONTENT.QUESTION');
marker('GENERAL.CONTENT.PRESENTATION');
marker('GENERAL.CONTENT.HTML');
marker('GENERAL.CONTENT.HTML FILE');
marker('GENERAL.CONTENT.SCORM');
// COMMONS
marker('GENERAL.SHOW_LESS');
marker('GENERAL.SHOW_MORE');
marker('GENERAL.VIEW');

// COMMONS MESSAGE
marker('GENERAL.SUCCESSFULLY_SUBSCRIBED');
marker('GENERAL.SUBSCRIPTION_REMOVED');

// COMMONS STATUS
marker('GENERAL.MISSION_STATUS.PROCESSING');
marker('GENERAL.MISSION_STATUS.INACTIVATED');
marker('GENERAL.MISSION_STATUS.IN_PROGRESS');
marker('GENERAL.MISSION_STATUS.IN_REVIEW');
marker('GENERAL.MISSION_STATUS.DONE');

// CATEGORIES
marker('GENERAL.CATEGORY.all');
marker('GENERAL.CATEGORY.Communications');
marker('GENERAL.CATEGORY.Design');
marker('GENERAL.CATEGORY.Development');
marker('GENERAL.CATEGORY.Digital Marketing');
marker('GENERAL.CATEGORY.Entrepreneurship');
marker('GENERAL.CATEGORY.Finance');
marker('GENERAL.CATEGORY.Financial Education');
marker('GENERAL.CATEGORY.Health and Fitness');
marker('GENERAL.CATEGORY.Language');
marker('GENERAL.CATEGORY.Leadership');
marker('GENERAL.CATEGORY.Lifestyle');
marker('GENERAL.CATEGORY.Management');
marker('GENERAL.CATEGORY.Marketing');
marker('GENERAL.CATEGORY.Office Productivity');
marker('GENERAL.CATEGORY.Personal Development');
marker('GENERAL.CATEGORY.Project Management');
marker('GENERAL.CATEGORY.Sales');
marker('GENERAL.CATEGORY.Social Media');
marker('GENERAL.CATEGORY.Strategy');
marker('GENERAL.CATEGORY.Technology');
marker('GENERAL.CATEGORY.Web Design');

marker('MISSION.LIVE.TITLE.NEW_MISSION');
marker('MISSION.LIVE.TITLE.EDIT_MISSION');

marker('MISSION.PRESENTIAL.TITLE.NEW_MISSION');
marker('MISSION.PRESENTIAL.TITLE.EDIT_MISSION');
marker('MISSION.PRESENTIAL.NOT_ENOUGH_VACANCIES.PLURAL');
marker('MISSION.PRESENTIAL.NOT_ENOUGH_VACANCIES.SINGULAR');

// Languages
marker('GENERAL.LANGUAGES.pt-br');
marker('GENERAL.LANGUAGES.es');
marker('GENERAL.LANGUAGES.es-co');
marker('GENERAL.LANGUAGES.pt-pt');
marker('GENERAL.LANGUAGES.en');

marker('GENERAL.TRANSFER');

// ENROLLMENTS
marker('ENROLLMENTS.MISSIONS.NO_ORBITING');
marker('ENROLLMENTS.MISSIONS.CONTINUE_MISSION');

marker('LEARNING_TRAIL.LIST.NO_ENROLLMENT');
marker('LEARNING_TRAIL.TOTAL_IN_PROGRESS.PLURAL');
marker('LEARNING_TRAIL.TOTAL_IN_PROGRESS.SINGULAR');
marker('LEARNING_TRAIL.DETAIL.FINISHED_AT');
marker('LEARNING_TRAIL.DETAIL.PROGRESS');
marker('LEARNING_TRAIL.DETAIL.CONSUMPTION');
marker('LEARNING_TRAIL.DETAIL.GIVE_UP_CONFIRMATION.TITLE');
marker('LEARNING_TRAIL.DETAIL.GIVE_UP_CONFIRMATION.MESSAGE');
marker('LEARNING_TRAIL.CONTINUE_TRAIL');

// Enrollment Status
marker('ENROLLMENT.TRACKING.TABLE.EMPTY');
marker('ENROLLMENT.TRACKING.TABLE.LOADING');
marker('ENROLLMENT.TRACKING.TABLE.CONTENT_DURATION');
marker('ENROLLMENT.TRACKING.TABLE.CONSUMPTION_STATUS_TYPE.green');
marker('ENROLLMENT.TRACKING.TABLE.CONSUMPTION_STATUS_TYPE.orange');
marker('ENROLLMENT.TRACKING.TABLE.CONSUMPTION_STATUS_TYPE.grey');

marker('ENROLLMENT.TABLE.EMPTY');
marker('ENROLLMENT.TABLE.LOADING');

marker('ENROLLMENT.TABLE.ENROLLED');
marker('ENROLLMENT.TABLE.STARTED');
marker('ENROLLMENT.TABLE.COMPLETED');
marker('ENROLLMENT.TABLE.PENDING_VALIDATION');
marker('ENROLLMENT.TABLE.REPROVED');
marker('ENROLLMENT.TABLE.REFUSED');
marker('ENROLLMENT.TABLE.EXPIRED');
marker('ENROLLMENT.TABLE.REQUEST_EXTENSION');

marker('ENROLLMENT.TOOLTIP.COMPLETED');
marker('ENROLLMENT.TOOLTIP.ENROLLED');
marker('ENROLLMENT.TOOLTIP.EXPIRED');
marker('ENROLLMENT.TOOLTIP.PENDING_VALIDATION');
marker('ENROLLMENT.TOOLTIP.REFUSED');
marker('ENROLLMENT.TOOLTIP.REPROVED');
marker('ENROLLMENT.TOOLTIP.REQUEST_EXTENSION');
marker('ENROLLMENT.TOOLTIP.STARTED');

// Enrollment Dialogs
marker('ENROLLMENT.DESCRIPTION.APPROVE');
marker('ENROLLMENT.DESCRIPTION.APPROVE_CERTIFICATE');
marker('ENROLLMENT.DESCRIPTION.REJECT_CERTIFICATE');
marker('ENROLLMENT.DESCRIPTION.RESTART');
marker('ENROLLMENT.DESCRIPTION.DELETE');
marker('ENROLLMENT.DESCRIPTION.EXTEND');

marker('ENROLLMENT.LABEL.APPROVE');
marker('ENROLLMENT.LABEL.APPROVE_CERTIFICATE');
marker('ENROLLMENT.LABEL.REJECT_CERTIFICATE');
marker('ENROLLMENT.LABEL.RESTART');
marker('ENROLLMENT.LABEL.DELETE');
marker('ENROLLMENT.LABEL.EXTEND');

marker('ENROLLMENT.TITLE.APPROVE');
marker('ENROLLMENT.TITLE.APPROVE_CERTIFICATE');
marker('ENROLLMENT.TITLE.HISTORIC');
marker('ENROLLMENT.TITLE.REJECT_CERTIFICATE');
marker('ENROLLMENT.TITLE.RESTART');
marker('ENROLLMENT.TITLE.DELETE');
marker('ENROLLMENT.TITLE.EXTEND');
marker('ENROLLMENT.TITLE.EXTERNAL');

marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.search');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.performance__lte');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.status');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.start_date__gte');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.start_date__lte');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.end_date__gte');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.end_date__lte');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.ordering');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.user__name');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.mission__name');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.start_date');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.end_date');
marker('ENROLLMENT.COLLECTION.FILTER_CHIPS.performance');

marker('WORKSPACE_CONFIGURATIONS.MODULES.Dashboard');
marker('WORKSPACE_CONFIGURATIONS.MODULES.Learning Trail');
marker('WORKSPACE_CONFIGURATIONS.MODULES.Pulse');
marker('WORKSPACE_CONFIGURATIONS.MODULES.Mission');
marker('WORKSPACE_CONFIGURATIONS.ENABLED_SERVICE_SUCCESS');
marker('WORKSPACE_CONFIGURATIONS.DISABLED_SERVICE_SUCCESS');

marker('ENROLLMENT.STATUS.COMPLETED');
marker('ENROLLMENT.STATUS.ENROLLED');
marker('ENROLLMENT.STATUS.EXPIRED');
marker('ENROLLMENT.STATUS.PENDING_VALIDATION');
marker('ENROLLMENT.STATUS.REFUSED');
marker('ENROLLMENT.STATUS.REPROVED');
marker('ENROLLMENT.STATUS.ENROLLMENT_REPROVED');
marker('ENROLLMENT.STATUS.REQUEST_EXTENSION');
marker('ENROLLMENT.STATUS.STARTED');
marker('ENROLLMENT.STATUS.INACTIVATED');
marker('ENROLLMENT.STATUS.GIVE_UP');

marker('ENROLLMENTS.TOOLTIP.STATUS.COMPLETED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ENROLLED');
marker('ENROLLMENTS.TOOLTIP.STATUS.EXPIRED');
marker('ENROLLMENTS.TOOLTIP.STATUS.PENDING_VALIDATION');
marker('ENROLLMENTS.TOOLTIP.STATUS.REFUSED');
marker('ENROLLMENTS.TOOLTIP.STATUS.REPROVED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ENROLLMENT_REPROVED');
marker('ENROLLMENTS.TOOLTIP.STATUS.REQUEST_EXTENSION');
marker('ENROLLMENTS.TOOLTIP.STATUS.STARTED');
marker('ENROLLMENTS.TOOLTIP.STATUS.INACTIVATED');
marker('ENROLLMENTS.TOOLTIP.STATUS.GIVE_UP');

marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.COMPLETED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.ENROLLED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.EXPIRED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.PENDING_VALIDATION');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.REFUSED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.REPROVED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.ENROLLMENT_REPROVED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.REQUEST_EXTENSION');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.STARTED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.INACTIVATED');
marker('ENROLLMENTS.TOOLTIP.STATUS.ADMIN.GIVE_UP');

marker('ENROLLMENTS.COMPLETED');
marker('ENROLLMENTS.REPROVED');
marker('ENROLLMENTS.PENDING_VALIDATION');

marker('ENROLLMENTS.reEnroll');
marker('ENROLLMENTS.viewMission');
marker('ENROLLMENTS.viewTrail');
marker('ENROLLMENTS.continue');
marker('ENROLLMENTS.previousEnrollments');
marker('ENROLLMENTS.attachCertificate');
marker('ENROLLMENTS.viewActivities');
marker('ENROLLMENTS.certificate');
marker('ENROLLMENTS.restart');
marker('ENROLLMENTS.retake');
marker('ENROLLMENTS.delete');
marker('ENROLLMENTS.giveUp');
marker('ENROLLMENTS.rejectCertificate');
marker('ENROLLMENTS.history');
marker('ENROLLMENTS.extendDeadline');
marker('ENROLLMENTS.extendDeadlineAdmin');
marker('ENROLLMENTS.approveEnrollment');
marker('ENROLLMENTS.approvePresentialLiveEnrollment');
marker('ENROLLMENTS.approveCertificate');
marker('ENROLLMENTS.refuseEnrollment');
marker('ENROLLMENTS.finishEnrollment');
marker('ENROLLMENTS.REFUSE_SUCCESS');
marker('ENROLLMENTS.linkCycle');

marker('ENROLLMENTS.TITLE.reEnroll');
marker('ENROLLMENTS.TITLE.viewMission');
marker('ENROLLMENTS.TITLE.viewTrail');
marker('ENROLLMENTS.TITLE.viewActivities');
marker('ENROLLMENTS.TITLE.certificate');
marker('ENROLLMENTS.TITLE.restart');
marker('ENROLLMENTS.TITLE.retake');
marker('ENROLLMENTS.TITLE.delete');
marker('ENROLLMENTS.TITLE.giveUp');
marker('ENROLLMENTS.TITLE.rejectCertificate');
marker('ENROLLMENTS.TITLE.history');
marker('ENROLLMENTS.TITLE.extendDeadline');
marker('ENROLLMENTS.TITLE.extendDeadlineAdmin');
marker('ENROLLMENTS.TITLE.approveEnrollment');
marker('ENROLLMENTS.TITLE.approveCertificate');
marker('ENROLLMENTS.TITLE.externalProvider');
marker('ENROLLMENTS.TITLE.refuseEnrollment');
marker('ENROLLMENTS.TITLE.finishEnrollment');
marker('ENROLLMENTS.TITLE.approvePresentialLiveEnrollment');

marker('ENROLLMENTS.MESSAGE.approveEnrollment');
marker('ENROLLMENTS.MESSAGE.reEnroll');
marker('ENROLLMENTS.MESSAGE.viewMission');
marker('ENROLLMENTS.MESSAGE.viewTrail');
marker('ENROLLMENTS.MESSAGE.certificate');
marker('ENROLLMENTS.MESSAGE.restart');
marker('ENROLLMENTS.MESSAGE.retake');
marker('ENROLLMENTS.MESSAGE.delete');
marker('ENROLLMENTS.MESSAGE.giveUp');
marker('ENROLLMENTS.MESSAGE.extendDeadline');

marker('ENROLLMENTS.MESSAGE.ADMIN.reEnroll');
marker('ENROLLMENTS.MESSAGE.ADMIN.viewMission');
marker('ENROLLMENTS.MESSAGE.ADMIN.viewTrail');
marker('ENROLLMENTS.MESSAGE.ADMIN.certificate');
marker('ENROLLMENTS.MESSAGE.ADMIN.restart');
marker('ENROLLMENTS.MESSAGE.ADMIN.retake');
marker('ENROLLMENTS.MESSAGE.ADMIN.delete');
marker('ENROLLMENTS.MESSAGE.ADMIN.extendDeadlineAdmin');
marker('ENROLLMENTS.MESSAGE.ADMIN.approveEnrollment');
marker('ENROLLMENTS.MESSAGE.ADMIN.rejectCertificate');
marker('ENROLLMENTS.MESSAGE.ADMIN.approveCertificate');
marker('ENROLLMENTS.MESSAGE.ADMIN.approvePresentialLiveEnrollment');
marker('ENROLLMENTS.MESSAGE.ADMIN.refuseEnrollment');
marker('ENROLLMENTS.MESSAGE.ADMIN.finishEnrollment');

marker('ENROLLMENTS.BUTTONS.reEnroll');
marker('ENROLLMENTS.BUTTONS.viewMission');
marker('ENROLLMENTS.BUTTONS.viewTrail');
marker('ENROLLMENTS.BUTTONS.viewActivities');
marker('ENROLLMENTS.BUTTONS.restart');
marker('ENROLLMENTS.BUTTONS.retake');
marker('ENROLLMENTS.BUTTONS.delete');
marker('ENROLLMENTS.BUTTONS.giveUp');
marker('ENROLLMENTS.BUTTONS.rejectCertificate');
marker('ENROLLMENTS.BUTTONS.history');
marker('ENROLLMENTS.BUTTONS.extendDeadline');
marker('ENROLLMENTS.BUTTONS.extendDeadlineAdmin');
marker('ENROLLMENTS.BUTTONS.approveEnrollment');
marker('ENROLLMENTS.BUTTONS.approveCertificate');
marker('ENROLLMENTS.BUTTONS.approvePresentialLiveEnrollment');
marker('ENROLLMENTS.BUTTONS.refuseEnrollment');
marker('ENROLLMENTS.BUTTONS.finishEnrollment');

marker('ENROLLMENTS.ERROR.EXTEND_GOAL_DATE_FAILURE');

marker('ENROLLMENTS.ERROR.user_mission_enrollment_in_progress_already_exists');
marker('ENROLLMENTS.ERROR.mission_enrollment_invalid_status');

marker('ENROLLMENTS.COLUMN.OVERDUE');
marker('ENROLLMENTS.COLUMN.REQUIRED');
marker('ENROLLMENTS.OVERDUE_BY.PLURAL');
marker('ENROLLMENTS.OVERDUE_BY.SINGULAR');

/**
 *
 * API ERROS
 */

// CHANNEL
marker('API.ERRORS.DELETE_CATEGORY_CHANNEL');

//MISSION
marker('API.ERRORS.MISSION_NOT_ENOUGH_DATA_TO_FINISH');
marker('API.ERRORS.USER_ENROLLMENT_PERFORMANCE_LOWER_THEN_MIN');
marker('API.ERRORS.USER_CONSUME_NOT_ENOUGH_TO_FINISH');
marker('API.ERRORS.USER_MISSION_ENROLLMENT_IN_PROGRESS_ALREADY_EXISTS');

// SCORM
marker('API.ERRORS.ERROR_TO_PARSE_XML_OR_UPLOAD_SCORM');
marker('API.ERRORS.ERROR_TO_PARSE_IMSMANIFEST_XML');
marker('API.ERRORS.MISSION_ENROLLMENT_ALREADY_FINISHED');

marker('API.ERRORS.IMANIFEST_FILE_NOT_FOUND');

// QUIZ

marker('QUIZ.ANSWER_ALREADY_EXIST');
marker('QUIZ.set_options_value');
marker('QUIZ.question_matching_query_does_not_exist');
marker('QUIZ.error_to_save_exam_answer');
marker('QUIZ.CONTENT.PULSE_UPDATED');
marker('QUIZ.CONTENT.PULSE_REMOVED_SUCCESS');
marker('QUIZ.CONTENT.PULSE_REMOVED_ERROR');
marker('QUIZ.CONTENT.ADDED_FAVORIT_SUCCESS');
marker('QUIZ.CONTENT.ADDED_FAVORIT_ERROR');
marker('QUIZ.CONTENT.REMOVE_QUIZ_SUCCESS');
marker('QUIZ.CONTENT.REMOVE_QUIZ_ERROR');
marker('QUIZ.CONTENT.UPDATE_PULSE_ERROR');
marker('QUIZ.CONTENT.CREATED');
marker('QUIZ.CONTENT.REALLY_DELETE_QUIZ');
marker('QUIZ.QUESTIONS');

marker('DASHBOARD.WAITING_FOR_CERTIFICATE');
marker('DASHBOARD.ENROLL');
marker('DASHBOARD.GOAL_FOR');
marker('DASHBOARD.LATE_IN');
marker('DASHBOARD.EXPIRES_IN');

// Mission Assessment Types
marker('GENERAL.ASSESSMENT.FULL');
marker('GENERAL.ASSESSMENT.CONTENT');
marker('GENERAL.ASSESSMENT.QUIZ');

// Pulses
marker('PULSES.LOAD_PULSE_LEARN_CONTENT_ERROR');
marker('PULSES.SUCCESSFULLY_ADDED');
marker('PULSES.SUCCESSFULLY_REMOVED');
marker('PULSES.BOOKMARK.SUCCESSFULLY_ADDED');
marker('PULSES.BOOKMARK.SUCCESSFULLY_REMOVED');

marker('MISSION.DETAIL.EVALUATIONS.COLLECTION.positives');
marker('MISSION.DETAIL.EVALUATIONS.COLLECTION.neutrals');
marker('MISSION.DETAIL.EVALUATIONS.COLLECTION.negatives');

marker('MISSION.ENROLLMENTS.TITLE');
marker('MISSION.ENROLLMENTS.SEATS.PLURAL');
marker('MISSION.ENROLLMENTS.SEATS.SINGULAR');
marker('MISSION.ENROLLMENTS.ENROLLED.PLURAL');
marker('MISSION.ENROLLMENTS.ENROLLED.SINGULAR');
marker('MISSION.ENROLLMENTS.MESSAGES.NO_ENROLLMENTS');
marker('MISSION.ENROLLMENTS.MESSAGES.APPROVE_SUCCESS');
marker('MISSION.ENROLLMENTS.MESSAGES.REFUSE_SUCCESS');
marker('MISSION.ENROLLMENTS.MESSAGES.DELETE_SUCCESS');
marker('MISSION.ENROLLMENTS.MESSAGES.APPROVED_EMAIL_SENT');
marker('MISSION.ENROLLMENTS.MESSAGES.BATCH_APPROVE_SUCCESS');
marker('MISSION.ENROLLMENTS.MESSAGES.BATCH_REFUSE_SUCCESS');
marker('MISSION.ENROLLMENTS.MESSAGES.BATCH_DELETE_SUCCESS');
marker('MISSION.ENROLLMENTS.MESSAGES.BATCH_APPROVED_EMAIL_SENT');
marker('MISSION.ENROLLMENTS.FILTER.TITLE');
marker('MISSION.ENROLLMENTS.FILTER.SEARCH_PLACEHOLDER');
marker('MISSION.ENROLLMENTS.STATUS.CONFIRMED');
marker('MISSION.ENROLLMENTS.STATUS.GIVE_UP');
marker('MISSION.ENROLLMENTS.FIELDS.OF');
marker('MISSION.ENROLLMENTS.FIELDS.NAME');
marker('MISSION.ENROLLMENTS.FIELDS.EMAIL');
marker('MISSION.ENROLLMENTS.FIELDS.DATE');
marker('MISSION.ENROLLMENTS.FIELDS.STATUS');
marker('MISSION.ENROLLMENTS.ACTIONS.APPROVE');
marker('MISSION.ENROLLMENTS.ACTIONS.RESEND_EMAIL');
marker('MISSION.ENROLLMENTS.ACTIONS.DELETE');
marker('MISSION.ENROLLMENTS.ACTIONS.SELECT_ALL');
marker('MISSION.ENROLLMENTS.ACTIONS.PRINT');
marker('MISSION.ENROLLMENTS.ACTIONS.SAVE');
marker('MISSION.CREATE_ENROLLMENTS.TITLE');
marker('MISSION.CREATE_ENROLLMENTS.SEARCH_PLACEHOLDER');
marker('MISSION.CREATE_ENROLLMENTS.IMPORT_USERS');
marker('MISSION.CREATE_ENROLLMENTS.DOWNLOAD_IMPORT_SHEET_SAMPLE');
marker('MISSION.CREATE_ENROLLMENTS.NO_USERS_SELECTED');
marker('MISSION.CREATE_ENROLLMENTS.CLEAR_ERRORED_USERS');
marker('MISSION.CREATE_ENROLLMENTS.ENROLL');
marker('MISSION.CREATE_ENROLLMENTS.ENROLL_SUCCESS_MESSAGE');
marker('MISSION.CREATE_ENROLLMENTS.SEATS.PLURAL');
marker('MISSION.CREATE_ENROLLMENTS.SEATS.SINGULAR');
marker('MISSION.CREATE_ENROLLMENTS.ERRORED_USERS.PLURAL');
marker('MISSION.CREATE_ENROLLMENTS.ERRORED_USERS.SINGULAR');
marker('MISSION.CREATE_ENROLLMENTS.USERS_ENROLLED.PLURAL');
marker('MISSION.CREATE_ENROLLMENTS.USERS_ENROLLED.SINGULAR');
marker('MISSION.CREATE_ENROLLMENTS.USER_NOT_FOUND');
marker('MISSION.GIVE_UP.CONFIRM_TITLE');
marker('MISSION.GIVE_UP.CONFIRM_PLACEHOLDER');

// Channel transfer
marker('TRANSFER_DIALOG.TITLE.CHANNEL');
marker('TRANSFER_DIALOG.SUBTITLE.CHANNEL');
marker('TRANSFER_DIALOG.TITLE.LEARNING_TRAIL');
marker('TRANSFER_DIALOG.SUBTITLE.LEARNING_TRAIL');

// Mission transfer
marker('MISSION.TRANSFER_DIALOG.SUBTITLE.DUPLICATE');
marker('MISSION.TRANSFER_DIALOG.SUBTITLE.SHARE');
marker('MISSION.TRANSFER_DIALOG.SUBTITLE.TRANSFER');
marker('MISSION.TRANSFER_DIALOG.INFO.DUPLICATE');
marker('MISSION.TRANSFER_DIALOG.INFO.SHARE');
marker('MISSION.TRANSFER_DIALOG.INFO.TRANSFER');
marker('MISSION.TRANSFER_DIALOG.TITLE.DUPLICATE');
marker('MISSION.TRANSFER_DIALOG.TITLE.SHARE');
marker('MISSION.TRANSFER_DIALOG.TITLE.TRANSFER');
marker('MISSION.TRANSFER_DIALOG.DESTINATION_TYPE.DUPLICATE.OTHER_WORKSPACE');
marker('MISSION.TRANSFER_DIALOG.DESTINATION_TYPE.DUPLICATE.SAME_WORKSPACE');
marker('MISSION.TRANSFER_DIALOG.DESTINATION_TYPE.SHARE.OTHER_WORKSPACE');
marker('MISSION.TRANSFER_DIALOG.DESTINATION_TYPE.TRANSFER.OTHER_WORKSPACE');
marker('MISSION.TRANSFER_DIALOG.DESTINATION_TYPE.TRANSFER.SAME_WORKSPACE');
marker('MISSION.TRANSFER_DIALOG.CONFIRMATION.TYPE.DUPLICATE');
marker('MISSION.TRANSFER_DIALOG.CONFIRMATION.TYPE.SHARE');
marker('MISSION.TRANSFER_DIALOG.CONFIRMATION.TYPE.TRANSFER');
marker('MISSION.TRANSFER_DIALOG.SUCCESS.DUPLICATE');
marker('MISSION.TRANSFER_DIALOG.SUCCESS.SHARE');
marker('MISSION.TRANSFER_DIALOG.SUCCESS.TRANSFER');

marker('TRANSFER.CANCEL.TITLE');
marker('TRANSFER.CANCEL.MESSAGE');
marker('TRANSFER.CANCEL.SUCCESS');
marker('TRANSFER.CANCEL.ERROR');
marker('TRANSFER.FILTER.DIALOG_TITLE');

marker('CHANNELS.SUBSCRIBED.SINGULAR');
marker('CHANNELS.SUBSCRIBED.PLURAL');

marker('GLOBAL_SEARCH.ENROLLABE_ITEM_OVERDUE.SINGULAR');
marker('GLOBAL_SEARCH.ENROLLABE_ITEM_OVERDUE.PLURAL');

marker('LEARNING_TRAIL_DETAIL.DUE_DAYS_TAG.SINGULAR');
marker('LEARNING_TRAIL_DETAIL.DUE_DAYS_TAG.PLURAL');
marker('LEARNING_TRAIL_DETAIL.EXPIRE_TAG');
marker('LEARNING_TRAIL_DETAIL.REQUIRED_TAG');
marker('LEARNING_TRAIL_DETAIL.TRAIL_GOAL_TAG');

marker('GAMIFICATION.SUCCESS_MESSAGE.MULTIPLIER_RANKING.ENABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.MULTIPLIER_RANKING.DISABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_BOARD.ENABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_BOARD.DISABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_SUB_DIRECTORATE.ENABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_SUB_DIRECTORATE.DISABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_AREA.ENABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_AREA.DISABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_LEADERSHIP.ENABLED');
marker('GAMIFICATION.SUCCESS_MESSAGE.RANKING_BY_LEADERSHIP.DISABLED');

marker('MISSION.ATTENDANCE_LIST.USERS_ENROLLED.PLURAL');
marker('MISSION.ATTENDANCE_LIST.USERS_ENROLLED.SINGULAR');
marker('MISSION.ATTENDANCE_LIST.USERS_REGISTERED.PLURAL');
marker('MISSION.ATTENDANCE_LIST.USERS_REGISTERED.SINGULAR');
marker('MISSION.ATTENDANCE_LIST.USERS_NOT_REGISTERED.PLURAL');
marker('MISSION.ATTENDANCE_LIST.USERS_NOT_REGISTERED.SINGULAR');
