export enum FilterGroupType {
  DATE_RANGE = 'DATE_RANGE',
  DATE = 'DATE',
  SELECT = 'SELECT',
  AUTOCOMPLETE_SELECT = 'AUTOCOMPLETE_SELECT',
  DURATION_RANGE = 'DURATION_RANGE',
  PERCENT_RANGE = 'PERCENT_RANGE',
  TEXT_FIELD = 'TEXT_FIELD',
}
