export enum EnrollmentStatuses {
  ENROLLED = 'ENROLLED',
  STARTED = 'STARTED',
  COMPLETED = 'COMPLETED',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  REPROVED = 'REPROVED',
  ENROLLMENT_REPROVED = 'ENROLLMENT_REPROVED',
  REFUSED = 'REFUSED',
  EXPIRED = 'EXPIRED',
  REQUEST_EXTENSION = 'REQUEST_EXTENSION',
  INACTIVATED = 'INACTIVATED',
  GIVE_UP = 'GIVE_UP',
  WAITING = 'WAITING',
}

export enum DevelopmentStatus {
  CLOSED = 'CLOSED',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
  IN_REVIEW = 'IN_REVIEW',
  INACTIVATED = 'INACTIVATED',
  IN_PROGRESS = 'IN_PROGRESS',
  INACTIVATED_BY_INTEGRATION = 'INACTIVATED_BY_INTEGRATION',
}
