import { marker } from '@jsverse/transloco-keys-manager/marker';

marker('UI.GENERAL.ACTIVE');
marker('UI.GENERAL.APPS_SERVICES.KONQUEST_LEARNING_TRAIL');
marker('UI.GENERAL.APPS_SERVICES.KONQUEST_MISSION');
marker('UI.GENERAL.APPS_SERVICES.KONQUEST_PULSE');
marker('UI.GENERAL.APPS_SERVICES.LEARN_ANALYTICS');
marker('UI.GENERAL.APPS_SERVICES.SMARTZAP');
marker('UI.GENERAL.CATEGORY.all');
marker('UI.GENERAL.CATEGORY.Communications');
marker('UI.GENERAL.CATEGORY.Design');
marker('UI.GENERAL.CATEGORY.Development');
marker('UI.GENERAL.CATEGORY.Digital Marketing');
marker('UI.GENERAL.CATEGORY.Entrepreneurship');
marker('UI.GENERAL.CATEGORY.Finance');
marker('UI.GENERAL.CATEGORY.Financial Education');
marker('UI.GENERAL.CATEGORY.Health and Fitness');
marker('UI.GENERAL.CATEGORY.Language');
marker('UI.GENERAL.CATEGORY.Leadership');
marker('UI.GENERAL.CATEGORY.Lifestyle');
marker('UI.GENERAL.CATEGORY.Management');
marker('UI.GENERAL.CATEGORY.Marketing');
marker('UI.GENERAL.CATEGORY.Office Productivity');
marker('UI.GENERAL.CATEGORY.Personal Development');
marker('UI.GENERAL.CATEGORY.Project Management');
marker('UI.GENERAL.CATEGORY.Sales');
marker('UI.GENERAL.CATEGORY.Social Media');
marker('UI.GENERAL.CATEGORY.Strategy');
marker('UI.GENERAL.CATEGORY.Technology');
marker('UI.GENERAL.CATEGORY.Web Design');
marker('UI.GENERAL.EMPTY_LIST_MESSAGE');
marker('UI.GENERAL.NOTIFICATION.CANT_MARK_AS_READ');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_COURSE_OVERVIEW_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_USER_OVERVIEW_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_ALL_USERS_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_ENROLLMENTS_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_EVALUATIONS_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_GROUPS_CHANNELS_USERS_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_GROUPS_MISSIONS_USERS_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_MISSIONS_QUIZ_ACTIVITIES_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_MISSIONS_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_OVERVIEW_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_PULSES_AND_CHANNELS_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_PULSES_QUIZ_ACTIVITIES_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.KONQUEST_WORKSPACE_USER_ACCESS_BY_DATE_REPORT_DONE');
marker('UI.GENERAL.NOTIFICATION.SMARTZAP_COURSE_OVERVIEW_REPORT_DONE');
marker('UI.GENERAL.VIEW_ALL');

marker('UI.WORKSPACE_DIALOG.INFORM_REASON');

// Languages
marker('UI.GENERAL.LANGUAGES.pt-br');
marker('UI.GENERAL.LANGUAGES.es');
marker('UI.GENERAL.LANGUAGES.es-co');
marker('UI.GENERAL.LANGUAGES.pt-pt');
marker('UI.GENERAL.LANGUAGES.en');

// CONTENTS TYPE
marker('UI.GENERAL.CONTENT.PDF');
marker('UI.GENERAL.CONTENT.VIDEO');
marker('UI.GENERAL.CONTENT.IMAGE');
marker('UI.GENERAL.CONTENT.PODCAST');
marker('UI.GENERAL.CONTENT.BLOG');
marker('UI.GENERAL.CONTENT.TEXT');
marker('UI.GENERAL.CONTENT.SPREADSHEET');
marker('UI.GENERAL.CONTENT.OTHERS');
marker('UI.GENERAL.CONTENT.QUESTION');
marker('UI.GENERAL.CONTENT.PRESENTATION');
marker('UI.GENERAL.CONTENT.HTML');
marker('UI.GENERAL.CONTENT.HTML FILE');
marker('UI.GENERAL.CONTENT.SCORM');

marker('UI.ENROLLMENT_LIST.OUTDATED.SINGULAR');
marker('UI.ENROLLMENT_LIST.OUTDATED.PLURAL');

// Filter Dialog
marker('UI.REPORT_FILTER_DIALOG.CONNECTOR.AND');
marker('UI.REPORT_FILTER_DIALOG.CONNECTOR.OR');
marker('UI.REPORT_FILTER_DIALOG.CONNECTOR.WHERE');
marker('UI.REPORT_FILTER_DIALOG.OPERATOR.IS_NOT');
marker('UI.REPORT_FILTER_DIALOG.OPERATOR.IT_IS');
marker('UI.REPORT_FILTER_DIALOG.OPERATOR.GREATER_THAN');
marker('UI.REPORT_FILTER_DIALOG.OPERATOR.LESS_THAN');

// Image upload info
marker('UI.IMAGE_UPLOAD_INFO.MISSION.BANNER_RES_INFO');
marker('UI.IMAGE_UPLOAD_INFO.MISSION.FAQ');
marker('UI.IMAGE_UPLOAD_INFO.MISSION.HELP_INFO');
marker('UI.IMAGE_UPLOAD_INFO.MISSION.RES_INFO');
marker('UI.IMAGE_UPLOAD_INFO.MISSION.TITLE');
marker('UI.IMAGE_UPLOAD_INFO.DEFAULT.RES_INFO');
marker('UI.IMAGE_UPLOAD_INFO.DEFAULT.TITLE');

marker('UI.MISSION.REQUIRED');

// GLOBAL SEARCH
marker('UI.GLOBAL_SEARCH.SEARCH');

marker('UI.LEARNING_TRAIL.DETAIL.RETAKE');
marker('UI.LEARNING_TRAIL.DETAIL.START');
marker('UI.LEARNING_TRAIL.DETAIL.GIVE_UP');
marker('UI.ENROLLMENT.STATUS.ENROLLED');
marker('UI.ENROLLMENT.STATUS.STARTED');
marker('UI.ENROLLMENT.STATUS.COMPLETED');
marker('UI.ENROLLMENT.STATUS.PENDING_VALIDATION');
marker('UI.ENROLLMENT.STATUS.REFUSED');
marker('UI.ENROLLMENT.STATUS.REPROVED');
marker('UI.ENROLLMENT.STATUS.ENROLLMENT_REPROVED');
marker('UI.ENROLLMENT.STATUS.EXPIRED');
marker('UI.ENROLLMENT.STATUS.REQUEST_EXTENSION');
marker('UI.ENROLLMENT.STATUS.GIVE_UP');
marker('UI.ENROLLMENT.STATUS.INACTIVATED');

marker('UI.ENROLLMENT.START');
marker('UI.ENROLLMENT.GOAL');
marker('UI.ENROLLMENT.OVERDUE.SINGULAR');
marker('UI.ENROLLMENT.OVERDUE.PLURAL');
marker('UI.ENROLLMENT.OVERDUE_LABEL');
marker('UI.ENROLLMENT.CONCLUSION');
marker('UI.ENROLLMENT.PERFORMANCE');
marker('UI.ENROLLMENT.REQUIRED');
marker('UI.ENROLLMENT.NO_DATA');

marker('UI.ENROLLMENT.ACTIONS.viewMission');
marker('UI.ENROLLMENT.ACTIONS.viewTrail');
marker('UI.ENROLLMENT.ACTIONS.continue');
marker('UI.ENROLLMENT.ACTIONS.reEnroll');
marker('UI.ENROLLMENT.ACTIONS.extendDeadline');
marker('UI.ENROLLMENT.ACTIONS.generateCertificate');
marker('UI.ENROLLMENT.ACTIONS.retake');

marker('UI.GENERAL.STATUS');
marker('UI.KP-FILTER.CATEGORY');

// MISSION MODEL
marker('UI.MISSION_MODEL');
marker('UI.MISSION_MODELS.INTERNAL');
marker('UI.MISSION_MODELS.EXTERNAL_PROVIDER');
marker('UI.MISSION_MODELS.LIVE');
marker('UI.MISSION_MODELS.PRESENTIAL');
marker('UI.MISSION_MODELS.SCORM');
