import { Pipe, PipeTransform } from '@angular/core';
import { USER_IMPORT_STATUS } from 'app/main/users/user-import-types';
import { ACTIVITY_LOG_STATUS_TAG_COLOR } from '@keeps-platform-frontend-workspace/kp-keeps';

const STATUS_COLOR_MAP: Record<USER_IMPORT_STATUS, string> = {
  [USER_IMPORT_STATUS.COMPLETED]: ACTIVITY_LOG_STATUS_TAG_COLOR.DONE,
  [USER_IMPORT_STATUS.COMPLETED_WITH_ERRORS]: ACTIVITY_LOG_STATUS_TAG_COLOR.DONE_WITH_EXCEPTIONS,
  [USER_IMPORT_STATUS.CONSOLIDATING]: ACTIVITY_LOG_STATUS_TAG_COLOR.PROCESSING,
  [USER_IMPORT_STATUS.FAILED]: ACTIVITY_LOG_STATUS_TAG_COLOR.ERROR,
  [USER_IMPORT_STATUS.PENDING]: ACTIVITY_LOG_STATUS_TAG_COLOR.CREATED,
  [USER_IMPORT_STATUS.PROCESSING]: ACTIVITY_LOG_STATUS_TAG_COLOR.PROCESSING,
  [USER_IMPORT_STATUS.READING]: ACTIVITY_LOG_STATUS_TAG_COLOR.PROCESSING,
};

@Pipe({
  name: 'userImportStatusColor',
})
export class UserImportStatusColorPipe implements PipeTransform {
  transform(status: USER_IMPORT_STATUS): string {
    return STATUS_COLOR_MAP[status] ?? status;
  }
}
