import { Pipe, PipeTransform } from '@angular/core';
import { USER_IMPORT_STATUS } from 'app/main/users/user-import-types';

const TRANSLATIONS_MAP: Record<USER_IMPORT_STATUS, string> = {
  [USER_IMPORT_STATUS.COMPLETED]: 'USERS.IMPORT_STATUS.COMPLETED',
  [USER_IMPORT_STATUS.COMPLETED_WITH_ERRORS]: 'USERS.IMPORT_STATUS.COMPLETED_WITH_ERRORS',
  [USER_IMPORT_STATUS.CONSOLIDATING]: 'USERS.IMPORT_STATUS.PROCESSING',
  [USER_IMPORT_STATUS.FAILED]: 'USERS.IMPORT_STATUS.FAILED',
  [USER_IMPORT_STATUS.PENDING]: 'USERS.IMPORT_STATUS.PENDING',
  [USER_IMPORT_STATUS.PROCESSING]: 'USERS.IMPORT_STATUS.PROCESSING',
  [USER_IMPORT_STATUS.READING]: 'USERS.IMPORT_STATUS.PROCESSING',
};

@Pipe({
  name: 'userImportStatus',
})
export class UserImportStatusPipe implements PipeTransform {
  transform(status: USER_IMPORT_STATUS): string {
    return TRANSLATIONS_MAP[status] ?? status;
  }
}
