import { marker } from '@jsverse/transloco-keys-manager/marker';

marker('GROUPS.DIALOG.REMOVE_GROUP_MESSAGE');
marker('GROUP_USER.DIALOG.REMOVE_USER_MESSAGE');
marker('GROUP_MISSION.DIALOG.REMOVE_MISSION_MESSAGE');
marker('GROUP_CHANNEL.DIALOG.REMOVE_CHANNEL_MESSAGE');
marker('GROUP_LEARNING_TRAIL.DIALOG.REMOVE_TRAIL_MESSAGE');

marker('GROUPS.DIALOG.EDIT_TITLE');
marker('GROUPS.DIALOG.CREATE_TITLE');
marker('GROUP_DETAIL.TAB.LINKED_TRAILS');
marker('GROUP_DETAIL.TAB.LINKED_USERS');
marker('GROUP_DETAIL.TAB.LINKED_MISSIONS');
marker('GROUP_DETAIL.TAB.LINKED_CHANNELS');
