import { KeepsNavigationItem } from '@keeps-platform-frontend-workspace/layout';

export const NAVIGATION_ITEMS: KeepsNavigationItem[] = [
  {
    id: 'home',
    title: 'Home',
    type: 'basic',
    icon: 'home',
    link: '/home',
    servicesIds: ['8d572fd1-cca9-4979-9e72-f3871ac8ee97'],
  },
  {
    id: 'dashboard',
    title: 'NAVIGATION.DASHBOARD',
    type: 'basic',
    svgIcon: 'dashboard',
    link: '/dashboard',
    servicesIds: ['0d3752f0-15d7-402a-8628-04ed47bcbf43'],
  },
  {
    id: 'learning-trail',
    title: 'NAVIGATION.TRAILS',
    type: 'basic',
    svgIcon: 'learning-trail',
    link: '/learning-trails',
    servicesIds: ['0d3752f0-15d7-402a-8628-04ed47bcbf42'],
  },
  {
    id: 'mission',
    title: 'NAVIGATION.MISSIONS',
    type: 'basic',
    icon: 'rocket_launch',
    link: '/missions',
    servicesIds: ['0d3752f0-15d7-402a-8628-04ed47bcbf41'],
  },
  {
    id: 'pulse',
    title: 'Feed',
    type: 'basic',
    icon: 'dynamic_feed',
    link: '/pulses-feed',
    servicesIds: ['f19a1f71-82fb-46df-ab88-bdd3700da124'],
  },
  {
    id: 'event',
    title: 'NAVIGATION.EVENTS',
    type: 'basic',
    icon: 'event',
    link: '/events',
    servicesIds: ['8064f5d7-e9cb-4bb8-8cb5-09030a14bf52'],
  },
  {
    id: 'enrollments',
    title: 'NAVIGATION.ENROLLMENTS',
    type: 'basic',
    icon: 'school',
    link: '/enrollments',
    servicesIds: ['0d3752f0-15d7-402a-8628-04ed47bcbf41', '0d3752f0-15d7-402a-8628-04ed47bcbf42'],
  },
  {
    id: 'gamification',
    title: 'Ranking',
    type: 'aside',
    icon: 'bar_chart',
    children: [
      {
        id: 'ranking',
        title: 'Ranking',
        type: 'basic',
        link: '/gamification/rankings',
      },
      {
        id: 'points-statement',
        title: 'NAVIGATION.POINTS_STATEMENT',
        type: 'basic',
        link: '/gamification/points-statement',
      },
    ],
    servicesIds: ['786f7dc6-5b82-4834-a7a4-6a938ed7dafc'],
  },
  {
    id: 'leader-panel',
    title: 'NAVIGATION.LEADER_PANEL',
    type: 'basic',
    icon: 'supervisor_account',
    link: '/leader-panel',
    roles: ['admin', 'super_admin'],
    classes: { wrapper: 'hidden xxs:block' },
  },
  { id: 'spacer', type: 'spacer' },
  {
    id: 'admin-settings',
    title: 'Admin',
    type: 'aside',
    icon: 'settings',
    roles: ['admin', 'super_admin', 'content', 'instructor'],
    classes: { wrapper: 'mt-auto hidden xxs:block' },
    children: [
      {
        id: 'admin-cluster-configuration',
        title: 'NAVIGATION.CONFIGURATION',
        type: 'group',
        roles: ['admin', 'super_admin'],
        classes: { wrapper: 'pointer-events-none' },
        children: [
          {
            id: 'settings',
            title: 'NAVIGATION.GENERAL',
            type: 'basic',
            link: '/settings/configurations',
            exactMatch: true,
            roles: ['admin', 'super_admin'],
          },
        ],
      },
      {
        id: 'admin-cluster-operation',
        title: 'NAVIGATION.OPERATION',
        type: 'group',
        roles: ['admin', 'super_admin', 'content', 'instructor'],
        classes: { wrapper: 'pointer-events-none' },
        children: [
          {
            id: 'content-management',
            title: 'NAVIGATION.CONTENT_MANAGEMENT',
            type: 'basic',
            link: '/management',
          },
          {
            id: 'enrollments',
            title: 'NAVIGATION.ENROLLMENTS',
            type: 'collapsable',
            children: [
              {
                id: 'trail-enrollments',
                title: 'NAVIGATION.TRAILS',
                type: 'basic',
                link: '/settings/learning-trails',
              },
              {
                id: 'mission-enrollments',
                title: 'NAVIGATION.MISSIONS',
                type: 'basic',
                link: '/settings/missions',
                exactMatch: true,
              },
              {
                id: 'event-enrollments',
                title: 'NAVIGATION.EVENTS',
                type: 'basic',
                link: '/settings/events',
                exactMatch: true,
              },
            ],
          },
          {
            id: 'normatives',
            title: 'NAVIGATION.NORMATIVES',
            type: 'basic',
            link: '/regulatory-compliance',
            servicesIds: ['6064f5d7-e9cb-4bb8-8cb5-09030a14bf5f'],
            roles: ['admin', 'super_admin'],
          },
        ],
      },
      {
        id: 'admin-cluster-personalization',
        title: 'NAVIGATION.PERSONALIZATION',
        type: 'group',
        roles: ['admin', 'super_admin'],
        classes: { wrapper: 'pointer-events-none' },
        children: [
          {
            id: 'custom-certificates',
            title: 'NAVIGATION.CUSTOM_CERTIFICATES',
            type: 'basic',
            link: '/custom-certificates',
            roles: ['admin', 'super_admin'],
          },
          {
            id: 'custom-sections',
            title: 'NAVIGATION.CUSTOM_SECTIONS',
            type: 'basic',
            link: '/custom-sections',
            roles: ['admin', 'super_admin'],
            servicesIds: ['8d572fd1-cca9-4979-9e72-f3871ac8ee97'],
          },
          {
            id: 'groups',
            title: 'NAVIGATION.GROUPS',
            type: 'basic',
            link: '/settings/groups',
            roles: ['admin', 'super_admin'],
          },
          {
            id: 'categories',
            title: 'NAVIGATION.CATEGORIES',
            type: 'basic',
            link: '/settings/categories',
            roles: ['admin', 'super_admin'],
          },
        ],
      },
      {
        id: 'admin-cluster-ecosystem',
        title: 'NAVIGATION.ECOSYSTEM',
        type: 'group',
        roles: ['admin', 'super_admin'],
        classes: { wrapper: 'pointer-events-none' },
        children: [
          {
            id: 'transfers',
            title: 'NAVIGATION.TRANSFERS',
            type: 'basic',
            link: '/settings/transfers',
            roles: ['admin', 'super_admin'],
          },
          {
            id: 'integrations',
            title: 'NAVIGATION.INTEGRATIONS',
            type: 'basic',
            link: '/integrations',
            roles: ['admin', 'super_admin'],
          },
          {
            id: 'marketplace',
            title: 'NAVIGATION.MARKETPLACE',
            type: 'basic',
            link: '/marketplace',
            roles: ['admin', 'super_admin'],
          },
        ],
      },
      {
        id: 'admin-cluster-audit',
        title: 'NAVIGATION.AUDIT',
        type: 'group',
        roles: ['super_admin'],
        classes: { wrapper: 'pointer-events-none' },
        children: [
          {
            id: 'activity-log',
            title: 'NAVIGATION.ACTIVITY_LOG',
            type: 'basic',
            link: '/settings/missions/activity-log',
            roles: ['super_admin'],
          },
        ],
      },
    ],
  },
];
